---
title: "Project EDA"
format: html
editor: visual
---

## Introduction



## Data

To start off we will explore the diabetes data set, beginning with importing the data and then naming categorical variable factors that correspond to the number codes of categorical variables.
```{r}
library(tidyverse)
diabetes <- read.csv("diabetes_binary_health_indicators_BRFSS2015.csv")

map_list <- list(
  Diabetes_binary = c("No Diabetes", "Diabetes") |> setNames(c(0,1)),
  HighBP = c("Normal", "High BP") |> setNames(c(0,1)),
  HighChol = c("Normal", "High Chol") |> setNames(c(0,1)),
  CholCheck = c("No", "Yes") |> setNames(c(0,1)),
  Smoker = c("No", "Yes") |> setNames(c(0,1)),
  Stroke = c("No", "Yes") |> setNames(c(0,1)),
  HeartDiseaseorAttack = c("No", "Yes") |> setNames(c(0,1)),
  PhysActivity = c("No", "Yes") |> setNames(c(0,1)),
  Fruits = c("No", "Yes") |> setNames(c(0,1)),
  Veggies = c("No", "Yes") |> setNames(c(0,1)),
  HvyAlcoholConsump = c("No", "Yes") |> setNames(c(0,1)),
  AnyHealthcare = c("No", "Yes") |> setNames(c(0,1)),
  NoDocbcCost = c("No", "Yes") |> setNames(c(0,1)),
  DiffWalk = c("No", "Yes") |> setNames(c(0,1)),
  Sex = c("Female", "Male") |> setNames(c(0,1))
)

diabetes <- diabetes |>
  mutate(across(
    intersect(names(diabetes), names(map_list)), ~factor(.x, levels = names(map_list[[cur_column()]]), labels = map_list[[cur_column()]]
    )
  ))
```

## Summarizations

Now that we have the data set available and with factor levels defined, we will now get several summarizations of the data.
```{r}
summary(diabetes$Diabetes_binary)
diabetes |> group_by(Diabetes_binary, Smoker) |> summarise(prop_diabetes = mean(Diabetes_binary))
diabetes |> group_by(Diabetes_binary, HighBP) |> summarise(count = n())

diabetes |> ggplot(aes(x = Diabetes_binary, y = BMI)) + geom_boxplot() + theme_minimal() + labs(title = "Diabetes rate by BMI", x = "Diabetes", y = "BMI")

diabetes |> ggplot(aes(x = HvyAlcoholConsump, fill = Diabetes_binary)) + geom_bar(position = "fill") + theme_minimal() + labs(title = "Diabetes vs Heavy Alcohol use", x = "Heavy Drinking", y = "Diabetes")
```
